=== ulrack/services/configuration/schema/service.compiler.extension.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "service.compiler.extension.schema.json",
    "type": "object",
    "properties": {
        "class": {
            "$ref": "definitions.json#definitions/classDeclaration"
        },
        "sortOrder": {
            "type": "integer",
            "minimum": 0
        },
        "key": {
            "$ref": "definitions.json#definitions/identifierDeclaration"
        },
        "parameters": {
            "type": "object"
        },
        "schema": {
            "$schema": "https://json-schema.org/draft-07/schema"
        }
    },
    "required": ["class", "sortOrder", "key"]
}

=== ulrack/services/configuration/service-compiler-extensions/services.extension.json
{
    "$schema": "../schema/service.compiler.extension.schema.json",
    "class": "\\Ulrack\\Services\\Component\\Compiler\\Extension\\ServicesCompiler",
    "sortOrder": 2,
    "key": "services",
    "schema": {
        "type": "object",
        "oneOf": [
            {
                "properties": {
                    "class": {
                        "type": "string",
                        "pattern": "^(\\\\[A-z]+)+$"
                    },
                    "parameters": {
                        "type": "object"
                    },
                    "abstract": {
                        "type": "boolean",
                        "default": false
                    }
                },
                "required": ["class"]
            },
            {
                "properties": {
                    "parent": {
                        "type": "string",
                        "pattern": "^[\\.\\w-]+$"
                    },
                    "parameters": {
                        "type": "object"
                    },
                    "abstract": {
                        "type": "boolean",
                        "default": false
                    }
                },
                "required": ["parent"]
            }
        ]
    }
}

=== ulrack/services/configuration/service-compiler-extensions/preferences.extension.json
{
    "$schema": "service.compiler.extension.schema.json",
    "class": "\\Ulrack\\Services\\Component\\Compiler\\Extension\\PreferencesCompiler",
    "sortOrder": 1,
    "key": "preferences",
    "parameters": {
        "service_keys": {
            "services": "class"
        }
    },
    "schema": {
        "type": "object",
        "properties": {
            "preference": {
                "type": "string",
                "pattern": "^(\\\\[A-z]+)+$"
            },
            "for": {
                "type": "string",
                "pattern": "^(\\\\[A-z]+)+$"
            }
        },
        "required": ["preference", "for"]
    }
}
